export type Category = {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  iconSet: "Ionicons" | "MaterialIcons" | "Feather" | "MaterialCommunityIcons";
  color: string;
  accentColor: string;
  count: number;
};

export type Listing = {
  id: string;
  categoryId: string;
  title: string;
  subtitle: string;
  location: string;
  rating: number;
  reviewCount: number;
  price?: string;
  phone?: string;
  verified: boolean;
  badge?: string;
  tags: string[];
  description: string;
  available?: boolean;
};

export const CATEGORIES: Category[] = [
  {
    id: "providers",
    title: "Service Providers",
    subtitle: "Skilled professionals at your fingertips",
    icon: "construct",
    iconSet: "Ionicons",
    color: "#1A5C38",
    accentColor: "#C9A84C",
    count: 4820,
  },
  {
    id: "businesses",
    title: "Businesses",
    subtitle: "Verified companies & organizations",
    icon: "business",
    iconSet: "Ionicons",
    color: "#1A3A5C",
    accentColor: "#6CA8E8",
    count: 2140,
  },
  {
    id: "emergency",
    title: "Emergency Services",
    subtitle: "Fast access when you need it most",
    icon: "warning",
    iconSet: "Ionicons",
    color: "#5C1A1A",
    accentColor: "#E85C5C",
    count: 340,
  },
  {
    id: "jobs",
    title: "Job Corner",
    subtitle: "Opportunities across Kenya",
    icon: "briefcase",
    iconSet: "Ionicons",
    color: "#3A1A5C",
    accentColor: "#A87AE8",
    count: 1890,
  },
  {
    id: "products",
    title: "Marketplace",
    subtitle: "Buy & sell products locally",
    icon: "storefront",
    iconSet: "MaterialIcons",
    color: "#1A4A5C",
    accentColor: "#5CC8E8",
    count: 6720,
  },
  {
    id: "realestate",
    title: "Real Estate",
    subtitle: "Properties across Kenya",
    icon: "home",
    iconSet: "Ionicons",
    color: "#3A5C1A",
    accentColor: "#88C84C",
    count: 3350,
  },
];

export const LISTINGS: Listing[] = [
  // Service Providers
  {
    id: "p1",
    categoryId: "providers",
    title: "James Mwangi",
    subtitle: "Master Plumber",
    location: "Westlands, Nairobi",
    rating: 4.9,
    reviewCount: 284,
    price: "KSh 2,500/hr",
    phone: "+254 712 345 678",
    verified: true,
    badge: "Top Rated",
    tags: ["Plumbing", "Pipe Repair", "Drainage"],
    description: "Professional plumber with 12 years experience. Specializes in residential and commercial plumbing, pipe installations, and emergency repairs.",
    available: true,
  },
  {
    id: "p2",
    categoryId: "providers",
    title: "Grace Wanjiku",
    subtitle: "Electrician",
    location: "Kilimani, Nairobi",
    rating: 4.8,
    reviewCount: 192,
    price: "KSh 3,000/hr",
    phone: "+254 723 456 789",
    verified: true,
    badge: "Verified Pro",
    tags: ["Electrical", "Wiring", "Solar"],
    description: "Certified electrician offering residential wiring, solar installations, and electrical fault diagnosis. Available for emergency callouts.",
    available: true,
  },
  {
    id: "p3",
    categoryId: "providers",
    title: "Peter Kamau",
    subtitle: "Painter & Decorator",
    location: "Lavington, Nairobi",
    rating: 4.7,
    reviewCount: 156,
    price: "KSh 1,800/hr",
    phone: "+254 734 567 890",
    verified: true,
    tags: ["Painting", "Decoration", "Renovation"],
    description: "Expert painter with an eye for detail. Interior and exterior painting, wallpaper installation, and full renovation services.",
    available: false,
  },
  {
    id: "p4",
    categoryId: "providers",
    title: "Mary Achieng",
    subtitle: "Home Cleaner",
    location: "Ngong Road, Nairobi",
    rating: 4.9,
    reviewCount: 421,
    price: "KSh 1,500/day",
    phone: "+254 745 678 901",
    verified: true,
    badge: "Top Rated",
    tags: ["Cleaning", "Laundry", "Organizing"],
    description: "Reliable and thorough domestic cleaner. Deep cleaning, regular maintenance, laundry services, and post-event cleanup.",
    available: true,
  },
  // Businesses
  {
    id: "b1",
    categoryId: "businesses",
    title: "Savannah Legal Associates",
    subtitle: "Law Firm",
    location: "Upper Hill, Nairobi",
    rating: 4.8,
    reviewCount: 87,
    phone: "+254 20 234 5678",
    verified: true,
    badge: "Premium",
    tags: ["Legal", "Corporate", "Property Law"],
    description: "Full-service law firm specializing in corporate law, real estate transactions, employment law, and dispute resolution.",
  },
  {
    id: "b2",
    categoryId: "businesses",
    title: "NairobiTech Solutions",
    subtitle: "IT & Software Company",
    location: "Gigiri, Nairobi",
    rating: 4.7,
    reviewCount: 134,
    phone: "+254 20 345 6789",
    verified: true,
    tags: ["Software", "IT Support", "Cybersecurity"],
    description: "Leading tech company offering custom software development, IT infrastructure, cloud solutions, and 24/7 technical support.",
  },
  {
    id: "b3",
    categoryId: "businesses",
    title: "Rift Valley Clinics",
    subtitle: "Medical Center",
    location: "Nakuru Town",
    rating: 4.9,
    reviewCount: 312,
    phone: "+254 51 234 5678",
    verified: true,
    badge: "Verified",
    tags: ["Healthcare", "Outpatient", "Pharmacy"],
    description: "Modern medical facility offering outpatient services, laboratory tests, pharmacy, dental care, and specialist consultations.",
  },
  // Emergency Services
  {
    id: "e1",
    categoryId: "emergency",
    title: "AAR Ambulance Services",
    subtitle: "Emergency Medical",
    location: "All Nairobi Areas",
    rating: 4.9,
    reviewCount: 1204,
    phone: "+254 20 717 1000",
    verified: true,
    badge: "24/7",
    tags: ["Ambulance", "ICU", "First Aid"],
    description: "Kenya's leading emergency ambulance service with fully equipped ICU ambulances and trained paramedics. Available 24/7 across Nairobi.",
    available: true,
  },
  {
    id: "e2",
    categoryId: "emergency",
    title: "National Police Service",
    subtitle: "Police Emergency",
    location: "Nationwide",
    rating: 4.5,
    reviewCount: 892,
    phone: "999",
    verified: true,
    badge: "Official",
    tags: ["Police", "Emergency", "Security"],
    description: "National emergency police number. Available 24/7 for crimes, accidents, and security emergencies across Kenya.",
    available: true,
  },
  {
    id: "e3",
    categoryId: "emergency",
    title: "Nairobi Fire Brigade",
    subtitle: "Fire & Rescue",
    location: "Nairobi Metro",
    rating: 4.7,
    reviewCount: 234,
    phone: "+254 20 222 2181",
    verified: true,
    badge: "24/7",
    tags: ["Fire", "Rescue", "Hazmat"],
    description: "City of Nairobi fire and rescue services. Responds to fires, road accidents, chemical spills, and trapped persons. Available 24/7.",
    available: true,
  },
  // Jobs
  {
    id: "j1",
    categoryId: "jobs",
    title: "Software Engineer",
    subtitle: "Andela Kenya",
    location: "Nairobi (Remote)",
    rating: 4.7,
    reviewCount: 42,
    price: "KSh 150,000 – 280,000/mo",
    verified: true,
    badge: "Hot",
    tags: ["React", "Node.js", "TypeScript"],
    description: "Join Andela as a Senior Software Engineer. Work on cutting-edge projects for global clients. Remote-first culture with competitive pay.",
    available: true,
  },
  {
    id: "j2",
    categoryId: "jobs",
    title: "Marketing Manager",
    subtitle: "Safaricom PLC",
    location: "Westlands, Nairobi",
    rating: 4.9,
    reviewCount: 28,
    price: "KSh 180,000 – 250,000/mo",
    verified: true,
    badge: "Urgent",
    tags: ["Marketing", "Digital", "Strategy"],
    description: "Lead marketing campaigns for Kenya's top telco. Requires 5+ years experience in digital marketing and brand management.",
    available: true,
  },
  {
    id: "j3",
    categoryId: "jobs",
    title: "Truck Driver",
    subtitle: "Kenya Transporters Ltd",
    location: "Mombasa Road, Nairobi",
    rating: 4.5,
    reviewCount: 65,
    price: "KSh 45,000 – 65,000/mo",
    verified: true,
    tags: ["Driving", "Logistics", "Class G License"],
    description: "Long-distance truck driver needed for Nairobi-Mombasa route. Valid Class G license required. Accommodation provided on route.",
    available: true,
  },
  // Products
  {
    id: "pr1",
    categoryId: "products",
    title: "Samsung Galaxy S24",
    subtitle: "Electronics",
    location: "CBD, Nairobi",
    rating: 4.8,
    reviewCount: 34,
    price: "KSh 78,000",
    phone: "+254 756 789 012",
    verified: true,
    badge: "New",
    tags: ["Phone", "Samsung", "Smartphone"],
    description: "Brand new Samsung Galaxy S24. 256GB storage, 8GB RAM. Original box with all accessories. One year warranty included.",
  },
  {
    id: "pr2",
    categoryId: "products",
    title: "L-Shaped Office Sofa",
    subtitle: "Furniture",
    location: "Industrial Area, Nairobi",
    rating: 4.6,
    reviewCount: 19,
    price: "KSh 38,500",
    phone: "+254 767 890 123",
    verified: true,
    tags: ["Sofa", "Furniture", "Office"],
    description: "High-quality L-shaped leather sofa, barely used. Dimensions: 280cm x 200cm. Dark brown color. Delivery available in Nairobi.",
  },
  {
    id: "pr3",
    categoryId: "products",
    title: "Toyota Hilux 2019",
    subtitle: "Vehicles",
    location: "Ngong Road, Nairobi",
    rating: 4.9,
    reviewCount: 8,
    price: "KSh 3,200,000",
    phone: "+254 778 901 234",
    verified: true,
    badge: "Featured",
    tags: ["4WD", "Toyota", "Pickup"],
    description: "2019 Toyota Hilux Double Cab 4x4. 82,000km, excellent condition. Full service history. Logbook ready for transfer.",
  },
  // Real Estate
  {
    id: "r1",
    categoryId: "realestate",
    title: "3BR Apartment – Kileleshwa",
    subtitle: "For Rent",
    location: "Kileleshwa, Nairobi",
    rating: 4.8,
    reviewCount: 12,
    price: "KSh 85,000/mo",
    phone: "+254 789 012 345",
    verified: true,
    badge: "New",
    tags: ["3 Bedrooms", "Swimming Pool", "Secure"],
    description: "Spacious 3-bedroom apartment in a prime secure estate. Ensuite master bedroom, modern kitchen, parking, pool, and 24hr security.",
    available: true,
  },
  {
    id: "r2",
    categoryId: "realestate",
    title: "Prime Land – Ruiru",
    subtitle: "For Sale",
    location: "Ruiru, Kiambu",
    rating: 4.7,
    reviewCount: 6,
    price: "KSh 4,500,000",
    phone: "+254 790 123 456",
    verified: true,
    tags: ["1/8 Acre", "Title Deed", "Perimeter Wall"],
    description: "Prime 1/8 acre plot in Ruiru. Ready title deed, perimeter wall, nearby tarmac road. Ideal for residential development.",
  },
  {
    id: "r3",
    categoryId: "realestate",
    title: "Commercial Office Space",
    subtitle: "For Rent",
    location: "Westlands, Nairobi",
    rating: 4.9,
    reviewCount: 23,
    price: "KSh 250,000/mo",
    phone: "+254 701 234 567",
    verified: true,
    badge: "Featured",
    tags: ["500 sqm", "Open Plan", "Fiber Ready"],
    description: "Premium office space in the heart of Westlands. 500 sqm, open plan, fiber internet, generator backup, 30 parking spots.",
    available: true,
  },
];
